name: notes
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.17

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets: 
    - assets/images/bg.svg
    - assets/images/notes.svg
    - assets/images/add.svg
  fonts:
    - family: Playwrite_RO
      fonts:
        - asset: assets/fonts/Playwrite_RO/PlaywriteRo-Regular.ttf
    - family: Roboto_Flex
      fonts:
        - asset: assets/fonts/Roboto_Flex/RobotoFlex.ttf
